### PR TITLE
Moved CSS files to dedicated directory

### PR DESCRIPTION
**Pull request by lucasjkr**
The .htaccess in the inc/ directory prevented CSS from being loaded, this fixes that.

### CODE REVIEW

**Comment by ZDi-it** [comment]
http://zdvid.com/r/

Works OK on my side. Which webserver are you using?

**Comment by lucasjkr** [comment]
I'm using apache 2.4.7

can you verify that the live site at www.zdvid.com/r/ has the .htaccess file in the inc/ directory (as it is in the repo)?

Regardless, CCS generally gets its own directory rather than being stored with php and config files :)

**Comment by ZDi-it** [comment]
Yes, it's my domain and testing base. Try visiting www.zdvid.com/r/inc
OK, I can merge your modifications, but I see you are removing a security feature I committed to admin/common.php 

Please double check!
Thanks =)

**Comment by ZDi-it** [comment]
Excellent work Lucas! The installation folder with the small setup is fantastic! I'll add SALT to the user password before storage using your setup.

I have updated the database connection script to PDO and create.php and go.php are working just fine. Thankfully you worked mostly on the install / admin part and it should merge fine after some small touch ups.

Let me know!

**Comment by lucasjkr** [comment]
Yeah, the install was my goal, but I had to touch on a few other things as I went.

You don't need to add salt to the passwords - PHP's password_hash function takes care of generating a secure, random salt already.

Thanks!

**Pull request merged**
